name: prints-usage
on:
    push:
        branches: [main]

jobs:
    print-usage:
        runs-on: ubuntu-latest
        steps:
            ## checkout
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "latest"
            ## build
            - run: npm ci
            - run: npm run build
            - run: node dist/index.js --help
