name: prints-usage
on:
    push:
        branches: [main]

jobs:
    print-usage:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/build-action
            - run: node dist/index.js --help
