name: prints-usage
on:
    push:
        branches: [main]

jobs:
    prints-usage:
        runs-on: ubuntu-latest
        steps:
            - uses: ./github/actions/build-actions/builds-latest-version.yml
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
