name: publish
on:
    push:
        branches: [main]

jobs:
    publish-to-npm:
        runs-on: ubuntu-latest
        steps:
            ## checkout
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "latest"
            ## build
            - run: npm ci
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
