name: publish
on:
    push:
        branches: [main]

jobs:
    publish-to-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/build-action
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
